# Generated by Django 4.1.5 on 2023-03-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='airpods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='описание товара')),
                ('create_time', models.DateTimeField(verbose_name='время воздания')),
            ],
            options={
                'verbose_name': 'наушники',
                'verbose_name_plural': 'наушник',
            },
        ),
        migrations.CreateModel(
            name='ipad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='описание товара')),
                ('create_time', models.DateTimeField(verbose_name='время воздания')),
            ],
            options={
                'verbose_name': 'айпады',
                'verbose_name_plural': 'айпад',
            },
        ),
        migrations.CreateModel(
            name='iphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='описание товара')),
                ('create_time', models.DateTimeField(verbose_name='время воздания')),
            ],
            options={
                'verbose_name': 'айфоны',
                'verbose_name_plural': 'айфон',
            },
        ),
        migrations.CreateModel(
            name='mac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='описание товара')),
                ('create_time', models.DateTimeField(verbose_name='время воздания')),
            ],
            options={
                'verbose_name': 'маки',
                'verbose_name_plural': 'мак',
            },
        ),
        migrations.CreateModel(
            name='watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='описание товара')),
                ('create_time', models.DateTimeField(verbose_name='время воздания')),
            ],
            options={
                'verbose_name': 'часики',
                'verbose_name_plural': 'часы',
            },
        ),
    ]
