# Generated by Django 4.1.5 on 2023-03-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Women',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'женщина',
                'verbose_name_plural': 'женщины',
            },
        ),
        migrations.AlterField(
            model_name='airpods',
            name='create_time',
            field=models.DateTimeField(verbose_name='время создание'),
        ),
        migrations.AlterField(
            model_name='ipad',
            name='create_time',
            field=models.DateTimeField(verbose_name='время создание'),
        ),
        migrations.AlterField(
            model_name='iphone',
            name='create_time',
            field=models.DateTimeField(verbose_name='время создание'),
        ),
        migrations.AlterField(
            model_name='mac',
            name='create_time',
            field=models.DateTimeField(verbose_name='время создание'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='create_time',
            field=models.DateTimeField(verbose_name='время создание'),
        ),
    ]
