# Generated by Django 4.1.5 on 2023-03-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_women_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airpods',
            name='description',
        ),
        migrations.AddField(
            model_name='airpods',
            name='content',
            field=models.TextField(blank=True, verbose_name='описание товара'),
        ),
        migrations.AddField(
            model_name='airpods',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='ipad',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='iphone',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='mac',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='watch',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='airpods',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ipad',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='iphone',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mac',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='watch',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='women',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='img'),
        ),
    ]
